### ISSUE TITLE
请教一下带后缀-r是什么意思

### ISSUE THREAD

**Issue by wwdok** [OlaWod/mfa#1]
作者您好，我最近在用MFA处理自己的aishell3格式的数据集，然后遇到您这个仓库了，我看您的仓库中的aishell3还有带后缀r的：
![image](https://user-images.githubusercontent.com/43233772/148157431-e596e516-c48a-4fd7-8abd-e573e2708836.png)
还有这个：
![image](https://user-images.githubusercontent.com/43233772/148157486-2bb1eeba-ba34-4959-88a6-e47614f89749.png)
请问这个后缀r代表什么意思呢，谢谢！

**Comment by OlaWod** [comment]
这两个lexicon是我从两个不同的地方偷过来的，它们的内容有一些不同，仅此而已

**Comment by wwdok** [comment]
是的，我对比了一下两者的内容：
![image](https://user-images.githubusercontent.com/43233772/148166603-e07469c8-b083-4906-8f2e-7f0c1a0e883f.png)
带r后缀版的有4120行，不带r后缀的有2003行。
带r后缀版的lexicon/txt后面部分很多拼音带有很多个r，我搞不懂这些r是什么意思
![image](https://user-images.githubusercontent.com/43233772/148166750-148c0b8c-ac7f-489c-b6e9-3f4fd0270aec.png)

**Comment by OlaWod** [comment]
带r的是儿化音的意思
比如：北京人 -> bei3 jing1 ren2 （无儿化音）/ bei3 jing1 renr2 （有儿化音）

**Comment by wwdok** [comment]
好的，谢谢！
